openapi: 3.1.0
info:
  title: Асистент клієнтського супроводу
  version: 1.0.0
  description: API для керування клієнтською базою Google Таблиць

servers:
  - url: https://agrobot-api-s8uz.onrender.com

paths:
  /add_or_update_client:
    post:
      operationId: addOrUpdateClient
      summary: Додати або оновити клієнта
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                назва:
                  type: string
                єдрпоу:
                  type: string
                область:
                  type: string
                район:
                  type: string
                площа:
                  type: number
                культура:
                  type: string
      responses:
        '200':
          description: Клієнт доданий або оновлений

  /delete_client:
    post:
      operationId: deleteClient
      summary: Видалити клієнта
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                назва:
                  type: string
      responses:
        '200':
          description: Клієнт видалений

  /list_columns:
    get:
      operationId: listColumns
      summary: Отримати список колонок
      responses:
        '200':
          description: Список колонок

  /get_client_by_partial_name:
    get:
      operationId: getClientByPartialName
      summary: Пошук клієнта за частковим збігом назви
      parameters:
        - name: name_part
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Знайдені клієнти

  /search_clients:
    get:
      operationId: searchClients
      summary: Пошук клієнтів за фільтрами
      parameters:
        - name: region
          in: query
          schema:
            type: string
        - name: district
          in: query
          schema:
            type: string
        - name: crop
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Список клієнтів, що відповідають критеріям

components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
