components:
  schemas:
    Farmer:
      properties:
        Культура:
          type: string
        Місяць:
          type: string
        Назва:
          type: string
        Область:
          type: string
        Площа:
          type: integer
        Потреба:
          type: string
        Примітка:
          type: string
        Телефон:
          type: string
      required:
      - Назва
      type: object
info:
  description: 'GPT-асистент агрокомпанії для роботи з базою клієнтів у Google Таблиці
    через API.

    Підтримує додавання, оновлення, пошук фермерів, зведення по регіонах, створення
    колонок.

    '
  title: Farmer CRM API
  version: 1.0.0
openapi: 3.1.0
paths:
  /add-column:
    post:
      operationId: addColumn
      parameters:
      - description: Назва нової колонки
        in: query
        name: column_name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Колонку додано
      summary: Додати нову колонку до таблиці
  /add-farmer:
    post:
      operationId: addFarmer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Farmer'
        required: true
      responses:
        '200':
          description: Фермера додано
        '400':
          description: Фермер уже існує
      summary: Додати нового фермера
  /farmer-names:
    get:
      operationId: getFarmerNames
      responses:
        '200':
          description: Повертає список назв
      summary: Отримати список імен фермерів
  /feedback-insights:
    get:
      operationId: getFeedbackInsights
      responses:
        '200':
          description: Інсайти враховано
      summary: Інсайти з фідбеку користувачів
  /filter-farmers:
    get:
      operationId: filterFarmers
      parameters:
      - in: query
        name: region
        required: false
        schema:
          type: string
      - in: query
        name: min_area
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: Фермери знайдені
      summary: Фільтрувати фермерів за регіоном та площею
  /find-farmer:
    get:
      operationId: findFarmer
      parameters:
      - in: query
        name: name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Результати пошуку
      summary: Знайти фермера за назвою
  /summary:
    get:
      operationId: getSummary
      responses:
        '200':
          description: Зведення по регіонах
      summary: Отримати зведення по регіонах
  /update-farmer:
    post:
      operationId: updateFarmer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Farmer'
        required: true
      responses:
        '200':
          description: Дані оновлено
        '404':
          description: Фермера не знайдено
      summary: Оновити дані фермера
servers:
- url: https://agrobot-api-s8uz.onrender.com
