openapi: 3.1.0
info:
  title: Farmer CRM API
  version: 1.0.0
  description: 'GPT-асистент агрокомпанії для роботи з базою клієнтів у Google Таблиці
    через API.

    Підтримує додавання, оновлення, пошук фермерів, зведення по регіонах, створення
    колонок.

    '
servers:
- url: https://agrobot-api-s8uz.onrender.com
paths:
  /add-farmer:
    post:
      operationId: addFarmer
      summary: Додати нового фермера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Farmer'
      responses:
        '200':
          description: Фермера додано
        '400':
          description: Фермер уже існує
  /update-farmer:
    post:
      operationId: updateFarmer
      summary: Оновити дані фермера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Farmer'
      responses:
        '200':
          description: Дані оновлено
        '404':
          description: Фермера не знайдено
  /find-farmer:
    get:
      operationId: findFarmer
      summary: Знайти фермера за назвою
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Результати пошуку
  /summary:
    get:
      operationId: getSummary
      summary: Отримати зведення по регіонах
      responses:
        '200':
          description: Зведення по регіонах
  /add-column:
    post:
      operationId: addColumn
      summary: Додати нову колонку
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                column_name:
                  type: string
      responses:
        '200':
          description: Колонку додано
components:
  schemas:
    Farmer:
      type: object
      properties:
        Назва:
          type: string
        Область:
          type: string
        Площа:
          type: integer
        Культура:
          type: string
        Телефон:
          type: string
        Потреба:
          type: string
        Місяць:
          type: string
        Примітка:
          type: string
      required:
      - Назва
